### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by AndrewJNorris** [OfficeDev/Project-Accelerator#21] opened 2021-03-22 13:41 UTC
The import of Project_for_the_web_Accelerator v1_6_0_18 import fails with the following error message

There are missing dependencies. Install the following solutions before installing this one: "msdyn_ProjectServiceCore (1.0.0.87)".

I already have msdyn_ProjectServiceCore > 1.0.0.87 installed.

I logged a ticket with support and they told me to try the suggested solution posted by matherton-pen in Issue #20 but I cannot uninstall all of the services.

The first two uninstalled ok but msdyn_ProjectServiceCore > 1.0.0.87 fails with an error:
Error code
8004F01D
Exception message
Solution dependencies exist, cannot uninstall. DependencyCount : 73 RequiredComponentObject details...
...followed by a long list of all the dependencies.

What should I do now please?

**Comment by BeReasonable** [comment] 2021-04-08 18:53
This is a duplicate of 
https://github.com/OfficeDev/Project-Accelerator/issues/20

**Closed** 2021-04-08 18:53 UTC
